version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    container_name: "neurovolt_db"
    environment:
      POSTGRES_DATABASE: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5433:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

#  server:
volumes:
  db-data: